remote_theme: qeacourse/minimal-mistakes@5a7a73b79e633162e05a134bf9ea0d25525dce24
logo: "https://qeacourse.github.io/RoboNinjaWarrior/website_graphics/olinlogo.png"
title: "CompRobo at Olin College"
repository: comprobo20/comprobo20.github.io
highlighter: rouge

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache


defaults:
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      toc: true
